version: '3'

services:
  jekyll:
    image: jekyll/jekyll:4
    command: bash -c "bundle install && bundle exec jekyll serve --watch --host 0.0.0.0"
    ports:
      - "4000:4000"
    volumes:
      - ./:/srv/jekyll
    working_dir: /srv/jekyll
    stdin_open: true
    tty: true
